version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    groups:
      storybook:
        patterns:
        - storybook
        - @storybook/*
        update-types:
        - "minor"
        - "patch"
    ignore:
    - dependency-name: "@storybook/*"
      update-types: ["version-update:semver-major"]
    - dependency-name: "storybook"
      update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
