name: CI

on: [push]

permissions:
  contents: write

jobs:
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          cache: "npm"
      - name: npm
        run: npm ci
      - name: stylelint
        run: npm run lint-style

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          cache: "npm"
      - name: npm
        run: npm ci
      - name: lint
        run: npm run lint-eslint

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          cache: "npm"
      - name: npm
        run: npm ci
      - name: prettier
        run: npm run lint-prettier

  jest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          cache: "npm"
      - name: npm
        run: npm ci
      - name: test
        run: npm test -- --coverage

  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' # Building is also part of the deployment action
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          cache: "npm"
      - name: npm
        run: npm ci
      - name: build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs:
      - stylelint
      - eslint
      - prettier
      - jest
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          cache: "npm"
      - name: npm
        run: npm ci
      - name: Build Storybook
        run: npm run build
      - name: Deploy Storybook
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
